replicaCount: 3
image:
  repository: ghcr.io/fatoubf/fatou-faye-gitops-app # 👈 Tout en MINUSCULES !
  tag: "latest"
  pullPolicy: Always
service:
  port: 80
  targetPort: 5000
namespace: fatou-faye-ns
