apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fatou-faye-release-ing
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fatou-faye-release-svc
                port:
                  number: {{ .Values.service.port }}
